using powerplant_coding_challenge.Model;

namespace powerplant_coding_challenge.Logic
{
    public static class Tools
    {
        // Set how much power each plant must generate
        public static void AffectLoadNeeded(IEnumerable<Powerplant> powerplants, int load)
        {
            var providedLoad = (double)0;

            foreach (var powerplant in powerplants)
            {
                if (providedLoad < load)
                {
                    if (powerplant.Type == PowerplantType.Windturbine)
                    {
                        providedLoad += powerplant.GeneratedPower;
                    }
                    else
                    {
                        var loadNeeded = load - providedLoad;

                        if (loadNeeded >= powerplant.Pmax)
                        {
                            powerplant.GeneratedPower = powerplant.Pmax;
                            providedLoad += powerplant.GeneratedPower;
                        }
                        else
                        {
                            powerplant.GeneratedPower = loadNeeded;
                            providedLoad += powerplant.GeneratedPower;
                        }
                    }
                }
                else
                {
                    powerplant.GeneratedPower = 0;
                }
            }
        }

        // Calculate how much energy will be generated by the wind power plant
        static double CalculateWindPower(Powerplant powerplant, double windPower)
        {
            return powerplant.Pmax * (windPower / 100);
        }

        // Returns list of wind power plants that fits the load criteria 
        public static void GetTotalWindPower(List<Powerplant> powerplants, int load, double windPower)
        {
            var totalWindPower = (double)0;

            foreach (var powerplant in powerplants)
            {
                // We only check for wind turbine power plants
                if (powerplant.Type == PowerplantType.Windturbine && totalWindPower < load)
                {
                    var generatedPower = CalculateWindPower(powerplant, windPower);

                    // If turning on the wind turbine exceeds load, then keep it off
                    if (totalWindPower + generatedPower > load)
                        powerplant.GeneratedPower = 0;
                    else
                    {
                        powerplant.GeneratedPower = generatedPower;

                        totalWindPower += generatedPower;
                    }
                }
            }
        }

        // Calculate price to generate 1 MW/h
        public static void SetMWhCost(List<Powerplant> powerplants, Fuels fuels)
        {
            foreach (var powerplant in powerplants)
            {
                if (powerplant.Type == PowerplantType.Windturbine)
                {
                    powerplant.CostPerMWh = 0;
                }
                else
                {
                    powerplant.CostPerMWh = GetFuelCost(powerplant.Efficiency, powerplant.Type, fuels);
                }
            }
        }

        // Set cost of operation of each power plant
        static double GetFuelCost(double efficiency, PowerplantType type, Fuels fuels)
        {
            var fuelCost = (double)0;
            var costOfMWh = (double)0;

            if (type == PowerplantType.Turbojet)
            {
                fuelCost = fuels.Kerosine;
            }
            else
            {
                fuelCost = fuels.Gas;
            }

            costOfMWh = (1 / efficiency) * fuelCost;

            return costOfMWh;
        }
    }
}
